# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.orc.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'orc', 'function_path': 'animated_java:orc/animations/pause_all'}
tag @s remove aj.orc.animation.animation.model.idol.playing
tag @s remove aj.orc.animation.animation.model.idol_to_walk.playing
tag @s remove aj.orc.animation.animation.model.walking.playing
tag @s remove aj.orc.animation.animation.model.spring.playing
tag @s remove aj.orc.animation.animation.model.attack1.playing
tag @s remove aj.orc.animation.animation.model.attack2.playing
tag @s remove aj.orc.animation.animation.model.attack3.playing
tag @s remove aj.orc.animation.animation.model.skill2_ready.playing
tag @s remove aj.orc.animation.animation.model.skill1.playing
tag @s remove aj.orc.animation.animation.model.skill2_start.playing
tag @s remove aj.orc.animation.animation.model.skill2_run.playing
tag @s remove aj.orc.animation.animation.model.dead.playing
tag @s remove aj.orc.animation.animation.model.skill_hb_start.playing
tag @s remove aj.orc.animation.animation.model.skill_hb_hold.playing