# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.orc.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'orc', 'function_path': 'animated_java:orc/animations/animation.model.attack2/play'}
tag @s add aj.orc.animation.animation.model.attack2.playing
scoreboard players set @s aj.animation.model.attack2.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:orc/animations/animation.model.attack2/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only