# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:orc/animations/animation.model.skill2_run/zzz/apply_frame {frame: 24}
scoreboard players add @s aj.animation.model.skill2_run.frame 1