# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.animation.model.idol.frame
scoreboard objectives remove aj.animation.model.idol_to_walk.frame
scoreboard objectives remove aj.animation.model.walking.frame
scoreboard objectives remove aj.animation.model.spring.frame
scoreboard objectives remove aj.animation.model.attack1.frame
scoreboard objectives remove aj.animation.model.attack2.frame
scoreboard objectives remove aj.animation.model.attack3.frame
scoreboard objectives remove aj.animation.model.skill2_ready.frame
scoreboard objectives remove aj.animation.model.skill1.frame
scoreboard objectives remove aj.animation.model.skill2_start.frame
scoreboard objectives remove aj.animation.model.skill2_run.frame
scoreboard objectives remove aj.animation.model.dead.frame
scoreboard objectives remove aj.animation.model.skill_hb_start.frame
scoreboard objectives remove aj.animation.model.skill_hb_hold.frame
tellraw @a [[{"text":"\n[","color":"gray"},{"text":"AJ","color":"aqua"},"] ",[{"text":"(from ","color":"gray","italic":true},"orc",")"]," -> "],{"text":"Successfully removed known animation scoreboard objectives.","color":"red"},{"text":"\nIf you have exported multiple times you may have to manually remove some objectives from previous exports manually, as Animated Java can only remove the latest export's objectives.","color":"gray","italic":true},["\n"]]