# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:orc/animations/animation.model.idol/zzz/apply_frame {frame: 80}
scoreboard players add @s aj.animation.model.idol.frame 1