# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone53] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone53 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone52] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone52 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone51] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone51 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone46] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone46 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone41] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone41 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.fst] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_fst set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone42] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone42 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.sec1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_sec1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone43] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone43 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.trd] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_trd set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.thumb] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_thumb set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone40] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone40 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone39] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone39 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone38] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone38 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone37] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone37 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone36] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone36 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.display12] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_display12 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone34] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone34 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone30] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone30 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.display11] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_display11 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone33] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone33 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone31] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone31 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone32] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone32 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone58] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone58 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.fst2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_fst2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone59] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone59 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.sec7] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_sec7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone60] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone60 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.trd2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_trd2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.thumb2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_thumb2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone61] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone61 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone57] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone57 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone55] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone55 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone54] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone54 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone56] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone56 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.display15] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_display15 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone35] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone35 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone44] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone44 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.display14] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_display14 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone18] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone18 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone19] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone19 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone29] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone29 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone49] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone49 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone50] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone50 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.neck] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_neck set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone47] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone47 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone48] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone48 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.display16] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_display16 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone28] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone28 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone23] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone23 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone22] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone22 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone24] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone24 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone20] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone20 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone25] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone25 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone26] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone26 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone27] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone27 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone21] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone21 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.display] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_display set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone7] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.display9] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_display9 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.knee] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_knee set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.main] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_main set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.sec] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_sec set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.sec2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_sec2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.sec3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_sec3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone14] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone14 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.display4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_display4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone12] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone12 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone13] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone13 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.display3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_display3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone11] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone11 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone10] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone10 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.display2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_display2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.display1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_display1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.knee2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_knee2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.main2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_main2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.sec4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_sec4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.sec5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_sec5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.sec6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_sec6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone17] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone17 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.display8] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_display8 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone15] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone15 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone16] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone16 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.display7] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_display7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone8] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone8 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.bone9] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone9 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.display6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_display6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.orc.node.display5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_display5 set from storage aj:uuid main.out