# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.orc.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'orc', 'function_path': 'animated_java:orc/animations/animation.model.skill2_run/apply_frame'}
data remove storage aj:temp args
$execute store result storage aj:temp args.frame int 1 run scoreboard players set @s aj.animation.model.skill2_run.frame $(frame)
execute at @s run function animated_java:orc/animations/animation.model.skill2_run/zzz/apply_frame with storage aj:temp args