# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute positioned ~ ~ ~ as @e[tag=!boss,distance=..2] as @s run damage @s 2 stiff:normal_damage at ~ ~ ~
execute positioned ~ ~ ~ run particle minecraft:crit ~ ~ ~ 0.5 0.5 0.5 0.1 128 force
execute positioned ~ ~ ~ run playsound minecraft:entity.player.attack.knockback ambient @a ~ ~ ~ 1 0.5 0.1