# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute positioned ~ ~ ~ as @e[tag=!boss,distance=..5] as @s run damage @s 14 stiff:hard_damage at ~ ~ ~
execute positioned ~ ~ ~ run particle minecraft:explosion ~ ~ ~ 1 1 1 1 64