# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:orc/animations/animation.model.walking/zzz/apply_frame {frame: 102}
scoreboard players add @s aj.animation.model.walking.frame 1