# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.orc.root] run return 0
execute on passengers if entity @s[tag=aj.orc.data] unless data entity @s {data:{rigHash: 'dde008d70ce165ab67941b325eb4803f7c3de6c2432fa6f496cb9cf46fd402ad'}} on vehicle run function animated_java:orc/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1