# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.orc.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.orc.animation.animation.model.idol.playing] run function animated_java:orc/animations/animation.model.idol/zzz/on_tick
execute if entity @s[tag=aj.orc.animation.animation.model.idol_to_walk.playing] run function animated_java:orc/animations/animation.model.idol_to_walk/zzz/on_tick
execute if entity @s[tag=aj.orc.animation.animation.model.walking.playing] run function animated_java:orc/animations/animation.model.walking/zzz/on_tick
execute if entity @s[tag=aj.orc.animation.animation.model.spring.playing] run function animated_java:orc/animations/animation.model.spring/zzz/on_tick
execute if entity @s[tag=aj.orc.animation.animation.model.attack1.playing] run function animated_java:orc/animations/animation.model.attack1/zzz/on_tick
execute if entity @s[tag=aj.orc.animation.animation.model.attack2.playing] run function animated_java:orc/animations/animation.model.attack2/zzz/on_tick
execute if entity @s[tag=aj.orc.animation.animation.model.attack3.playing] run function animated_java:orc/animations/animation.model.attack3/zzz/on_tick
execute if entity @s[tag=aj.orc.animation.animation.model.skill2_ready.playing] run function animated_java:orc/animations/animation.model.skill2_ready/zzz/on_tick
execute if entity @s[tag=aj.orc.animation.animation.model.skill1.playing] run function animated_java:orc/animations/animation.model.skill1/zzz/on_tick
execute if entity @s[tag=aj.orc.animation.animation.model.skill2_start.playing] run function animated_java:orc/animations/animation.model.skill2_start/zzz/on_tick
execute if entity @s[tag=aj.orc.animation.animation.model.skill2_run.playing] run function animated_java:orc/animations/animation.model.skill2_run/zzz/on_tick
execute if entity @s[tag=aj.orc.animation.animation.model.dead.playing] run function animated_java:orc/animations/animation.model.dead/zzz/on_tick
execute if entity @s[tag=aj.orc.animation.animation.model.skill_hb_start.playing] run function animated_java:orc/animations/animation.model.skill_hb_start/zzz/on_tick
execute if entity @s[tag=aj.orc.animation.animation.model.skill_hb_hold.playing] run function animated_java:orc/animations/animation.model.skill_hb_hold/zzz/on_tick
execute on passengers if entity @s[tag=aj.orc.data] run function animated_java:orc/root/zzz/on_tick/locators_and_cameras
execute at @s on passengers run rotate @s ~ ~